### ISSUE TITLE
When the component unmount

### ISSUE THREAD

**Issue by filenwind** [krasimir/react-cssx#2]
Hi Krasimir,

I found that when components unmounted, the style tag in the head is still there.
I think it will be the problem when the project huge. ( ex. using react router)

Is it possible to clean style tag in the head when component is unmounted?

Thanks :D

**Comment by krasimir** [comment]
Definitely. Thanks for reporting. I'll try resolving this during the weekend.

**Comment by krasimir** [comment]
Sorry for the big delay. It's fixed now in `1.1.1` version.
