### ISSUE TITLE
Parsing error: Unexpected token

### ISSUE THREAD

**Issue by CharGrnmn** [krasimir/react-cssx#3]
I am receiving a parsing error on the  `color: {{ color }};` part of the code. Using webpack build, was wondering if you ran into this issue, and if not, I will supply more code to tackle specific problem .

```
styleParagraph(color, text) {
     return (
       <style>
         p {
           color: {{ color }};
         }
         p::before {
           content: {{ text }};
         }
       </style>
     );
   }
```

**Comment by krasimir** [comment]
Hi @CharlieGreenman,

Can you please post your webpack config file. I have the feeling that babel (I assume that you are using babel because of the method definition) is taking the code first. CSSX transpiler should go through the code before babel otherwise [babylon](https://github.com/babel/babylon) tries parsing the code as jsx.

**Comment by CharGrnmn** [comment]
Here is my full webpack config: 

```
var path = require("path");
var open = require("open");
//for legac systems
require('es6-promise').polyfill();

//a little bit of glitch before page opens,
//works well otherwise
open("http://localhost:8080/");

module.exports = {
    entry: [
        //'webpack/hot/dev-server',
        'webpack-dev-server/client?http://localhost:8080',
        path.resolve(__dirname, 'app/js/main.js')
    ],
    output: {
        path: path.resolve(__dirname, './dist/js'),
        publicPath: 'js',
        filename: 'bundle.js'
    },
    debug: true,
    devtool: "#eval-source-map",
    module: {
        preLoaders: [
            {test: /\.js$/, loader: "eslint-loader",  exclude: /node_modules/ }
        ],
        //https://github.com/Flipboard/react-canvas/issues/102
        loaders: [
            {test: /\.scss$/,loaders: [
              "style",
               "css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]",
               "autoprefixer-loader",
               "sass"]},
            {test: /\.jade/, loader: "jade" },
            {test: /\.js?$/, exclude: /node_modules/, loader: 'babel',
                query: {
                    presets: ['es2015', 'react']
                }
            },
            {
              test: /(\.js|\.jsx)$/,
              loader: 'cssx-loader',
              exclude: /node_modules/
            }
        ],
        resolve: {
            extensions: ['', '.js', '.jsx']
        }
    },
    eslint: {
        configFile: '.eslintrc'
    }
};

```

**Comment by krasimir** [comment]
Thanks. I'll investigate.

**Comment by CharGrnmn** [comment]
I also what to point out, it worked. The styling made it through, it's just that the console kept bringing up an unnecessary error.

**Comment by krasimir** [comment]
Ah that's interesting and it will probably move my investigation in another direction. Can I see your app somewhere or at least a simple page that replicates the issue.

**Comment by CharGrnmn** [comment]
Yes, current app can be found here: https://github.com/CharlieGreenman/pixelLight - If I end up changing it, I will make a branch and put it here. In the meantime, master is ready to go. 

File it is being used in, can be seen here: https://github.com/CharlieGreenman/pixelLight/blob/master/app/js/components/color-picker/pixel-color-picker.js

**Comment by krasimir** [comment]
Hey, I just forked your project. The error that we are getting is because of the `preLoaders` section of your webpack config.

```
preLoaders: [
    {
        test: /\.js$/,
        loader: "eslint-loader",
        exclude: /node_modules/
    }
]
```

eslint don't understand CSSX syntax and says that it's invalid. You may solve the issue by adding a `.eslintignore` in your project and list all the files that contain CSSX syntax.

Also can you please bump the versions of **cssx-loader** to **5.0.0** and **react-cssx** to **1.1.1**.

**Comment by CharGrnmn** [comment]
Hey Krasimir, thank you. Sometimes I forget that eslint still works behind the scenes even with no config values. I didn't have a chance to get around to your reccomended implementation yet. However, cssx-loader, react-cssx as well as eslint have been bumped up to latest version. I am going to try to use eslint-disable instead of the .eslintignore and see where that goes. Will close once that works. My thanks and apologies once again. Maybe I'll put in a cssx option for eslint this weekend.

**Comment by krasimir** [comment]
No worries. I have the feeling that making eslint understand CSSX will be difficult.
