### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by zvictor** [krasimir/react-cssx#6]
How can I run `npm run build` myself? I tried running it after `npm i` and that's the output I get:

``` haskell
⚡ npm run build

> react-cssx@1.1.1 build /myProject/src/node_modules/react-cssx
> webpack

Hash: fd9b16d15a7108486302
Version: webpack 1.12.14
Time: 33ms
    + 1 hidden modules

ERROR in ./src/CSSX.jsx
Module parse failed: /myProject/src/node_modules/react-cssx/src/CSSX.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React from 'react';
| import 'cssx';
|
```

**Comment by krasimir** [comment]
Can you please delete your `node_modules` directory and try again. I just downloaded the repo and did the same. It works on my machine.

P.S.
also let me know your OS, node and npm version. Thanks.

**Comment by zvictor** [comment]
I just found the problem. I had cloned this repo inside a `node_modules` folder and it messed up the dependencies loader.
